apiVersion: v1
kind: Secret
metadata:
  name: runner-ssh-key
  labels:
    {{- include "runner-utils.labels" . | nindent 4 }}
data:
  id_rsa: |
    {{ .Values.runner.sshIdRsa | b64enc }}
  known_hosts: |
    {{ .Values.runner.sshKnownHosts | b64enc }}
type: Opaque