apiVersion: v1
kind: Secret
metadata:
  name: runner-helm-secret-key
  labels:
    {{- include "runner-utils.labels" . | nindent 4 }}
data:
  dev.key: |
    {{ .Values.runner.helmSecretsKeyDev | b64enc }}
  staging.key: |
    {{ .Values.runner.helmSecretsKeyStaging | b64enc }}
  production.key: |
    {{ .Values.runner.helmSecretsKeyProduction | b64enc }}
type: Opaque
