config:
    test: ENC[AES256_GCM,data:z9T/og==,iv:uQiCNf1zf5w1pVaD20RX0d3uaoSDrKSJRZFox29EKHc=,tag:jOkjaA16rTKay6RfT6cPyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-13T03:25:19Z"
    mac: ENC[AES256_GCM,data:GSVL9YrNvki7B5cjrDhauIFQ1BoxKwoHhdDzFxK48NiqvcInGyQ6c+Zf6kyx4Zf+HHE2tqG8pujoxGJe3PVFp0kdCucSIxbq5yWtfVq56PIP3zc7z8aZJUY6kBX6jiynLEkoSZRKXt0ZXwgQbP6dfy6lwOFE9B0e7FE49oVpHT8=,iv:wx7xcXMz/Um9jfrgtcMn804M/ZfCx0rhOPjkch3cbw8=,tag:gYKCAOjbbI/Mlg7d3FhWyg==,type:str]
    pgp:
        - created_at: "2023-03-13T03:25:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA0eUlmxxVLe/ARAAla4/aH6UV3qeixUjYi12XHjvYsQutob6YJ+vZnPxDMWq
            as+MFCgNZ3vjivUsEokSJUKYObvz/14oR/rIo/wEAos3md2iOPLfA2qBYcyJxopE
            8Qw9m2WqF6ZJ1NEoN8h9UxKbAJA7rj32qXpzrh4rll9Wct23RMcfaN6DjG2jw5f5
            eEfykEBcnNQpb1LC6pDVtg6stu3NeejB7tzYhhWfdBjsyis3PndgImBufm5DUSLl
            eOdJinub0rTR6O0jSEeStRS4gt0945Uo4wagxGF8qAHgC10jtB/eWR/azyV3zuJN
            1Bp5yOTRoTe4ZogE/rapuZADCSWdpS7vjgKS5BlhvaLwntUCeW7CxQXhRA5LIfoe
            F1dLC9xfIlPbHzHBq7JHMZUGFisdNCtJjkChlN82Rn+/0KH0YozBThaE/u0aZR4x
            cJSaEXNUfYF6FVnPWUA5LuDz+WxBctVISq22ywKKBbWIzPReuOYYQjHOSArZt8ri
            3Y0WKOW3gesovoAvVXa/3dVV06szHQJi8ZoksgghzjaWjyNG6K7P75SM1nE3WloD
            j6Vt3bAn/4rVg8lLQzdM73cCk59VimIu0FKfKPQ+j5OzZk9/YEEe0SXzFK4KUJU4
            DevqEL5FcNUA2bE+B9QeGhubNNv8oLE4bsedZU+hG/ONDxPdOmeHdLHGBe3NCHDU
            aAEJAhCT2+PLo4yIEsVPMo2SR0ubKX4f+tOgtY5S4FbtpAwVXWnliUqvaRVQIoO7
            6vuS1NKeYF4xiUWR0FJ8Kxw/a/IObnHf25kyqUGMIno1Lw3scJaxgPWXww4uZPkY
            gRlzrGq0hvbe
            =VZTi
            -----END PGP MESSAGE-----
          fp: 0EBCF19B005C56730E1C08D5F52B8A523D9D6CAF
    unencrypted_suffix: _unencrypted
    version: 3.7.3
