apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: stagingresolver
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: info@antikode.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: stagingresolver
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx
