{{- $fullName := include "nextjs-fe.fullname" . -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nextjs-fe.fullname" . }}
  labels:
    {{- include "nextjs-fe.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nextjs-fe.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        checksum/nginx-conf: {{ include (print $.Template.BasePath "/configmap/nginx-conf.yaml") . | sha256sum }}
        checksum/nginx: {{ include (print $.Template.BasePath "/configmap/nginx.yaml") . | sha256sum }}
        checksum/CORS: {{ include (print $.Template.BasePath "/configmap/CORS.yaml") . | sha256sum }}
      labels:
        {{- include "nextjs-fe.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: nginx-conf-volume
          configMap:
            name: {{ include "nextjs-fe.fullname" . }}-nginx-conf
        - name: nginx-volume
          configMap:
            name: {{ include "nextjs-fe.fullname" . }}-nginx
        - name: cors-volume
          configMap:
            name: {{ include "nextjs-fe.fullname" . }}-cors
        - name: env-nextjs-fe-volume
          configMap:
            name: {{ include "nextjs-fe.fullname" . }}-env
      containers:
        - name: {{ include "nextjs-fe.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: env-nextjs-fe-volume
              mountPath: /home/app/site/.env
              subPath: .env
          env:
            - name: env
              value: {{ .Values.appEnvironment }}
            {{- range $name, $val := .Values.customEnvVar }}
            - name: '{{ $name }}'
              value: '{{ $val }}'
            {{- end }}
          command:
            - bash
            - -c
            - "{{ if .Values.pm2.enabled }}
              pm2-runtime start npm --name '{{ $fullName }}' -- start
              {{ else }}
              npm run start
              {{ end }}"
          ports:
            - name: nextjs-fe-http
              containerPort: 8083
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: {{ include "nextjs-fe.fullname" . }}-nginx
          image: nginx:1.18.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: nginx-conf-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-volume
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: cors-volume
              mountPath: /etc/nginx/CORS.rule
              subPath: CORS.rule
          ports:
            - name: nginx
              containerPort: 80
              protocol: TCP
          {{ if .Values.cattleAutoscaling.enabled }}
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
          {{ end }}
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 40
            periodSeconds: 10
            failureThreshold: 5
            successThreshold: 1
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}