apiVersion: v1
kind: Service
metadata:
  name: {{ include "nextjs-fe.fullname" . }}
  labels:
    {{- include "nextjs-fe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nginx
      protocol: TCP
      name: nginx
    - port: 8083
      targetPort: 8083
      name: nextjs-fe-http
  selector:
    {{- include "nextjs-fe.selectorLabels" . | nindent 4 }}
