# Default values for nextjs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: asia-southeast1-docker.pkg.dev/alfath-386215/dev/nextjs-fe
  pullPolicy: IfNotPresent
  tag: bc5e72aa9c0a70e3173c288d03861fc200730246
# imagePullSecrets:
#   - name: gcr-json-key
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 80
ingress:
  enabled: false
  hostName: fe.alfathmad.xyz
  enableTls: true
  annotations: {}
resources:
  limits:
    cpu: 150m
    memory: 150Mi
  requests:
    cpu: 75m
    memory: 75Mi
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
