templates:
  default: &default
    # chart: stable/{{`{{ .Release.Name }}`}}
    # namespace: default
    # This prevents helmfile exiting when it encounters a missing file
    # Valid values are "Error", "Warn", "Info", "Debug". The default is "Error"
    # Use "Debug" to make missing files errors invisible at the default log level(--log-level=INFO)
    missingFileHandler: Warn
    values:
    - values/production/{{`{{ .Release.Name }}`}}/values.yaml
    secrets:
    - values/production/{{`{{ .Release.Name }}`}}/secrets.yaml

helmDefaults:
  kubeContext: gke_alfath-386215_asia-southeast1-a_production
  timeout: 1200

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: stable
  url: https://charts.helm.sh/stable
- name: prometheus-community
  url: https://prometheus-community.github.io/helm-charts
- name: grafana
  url: https://grafana.github.io/helm-charts
- name: nginx-stable
  url: https://helm.nginx.com/stable
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: cert-manager
  url: https://charts.jetstack.io
- name: eks-charts
  url: https://aws.github.io/eks-charts

releases:
- name: nextjs-fe
  <<: *default
  namespace: nextjs
  installed: true
  chart: ../chart/nextjs-fe

- name: nextjs-fe-be
  <<: *default
  namespace: nextjs
  installed: true
  chart: ../chart/nextjs-be

- name: ingress-nginx
  namespace: nginx
  <<: *default
  chart: ingress-nginx/ingress-nginx
  version: 4.7.0

- name: cert-manager
  <<: *default
  namespace: cert-manager
  chart: jetstack/cert-manager
  version: 1.10.0

- name: grafana
  <<: *default
  namespace: monitoring
  chart: grafana/grafana
  version: 6.52.4

- name: prometheus
  <<: *default
  namespace: monitoring
  installed: true
  chart: prometheus-community/prometheus
  version: 20.0.1